settings.outformat = "png";
defaultpen(fontsize(14pt));
import geometry;

unitsize(4cm);
size(12cm);

pair a = (0, 2);
pair b = (-1.5, 0);
pair c = (1.5, 1);
triangle t = triangle(a,b,c);
show(t, La="", Lb="", Lc="", 0.7*green);
pair i1 = excenter(opposite(t.VA));
dot(i1);
label("$I_1$", i1, align=SW, 0.5*green+0.8*blue);
pair i2 = excenter(opposite(t.VB));
dot(i2);
label("$I_2$", i2, align=SE, 0.5*green+0.8*blue);
pair i3 = excenter(opposite(t.VC));
dot(i3);
label("$I_3$", i3, align=SW, 0.5*green+0.8*blue);
circle c1 = circle(t);
pair o = circumcenter(t);
dot(o);
pair i = incenter(t);
dot(i);
label("$I$", i, align=SW, 0.5*green+0.8*blue);
label("$O$", o, align=SW, 0.5*green+0.8*blue);
draw(c1, 0.7*green);
line t1[] = tangents(c1, i1);
pair p1[] = intersectionpoints(c1, t1[0]);
draw(i1 -- p1[0], 0.8*red);
draw(o -- p1[0], 0.8*red);
pair p1[] = intersectionpoints(c1, t1[1]);
draw(i1 -- p1[0], 0.8*red);
draw(o -- p1[0], 0.8*red);
line t1[] = tangents(c1, i2);
pair p1[] = intersectionpoints(c1, t1[0]);
draw(i2 -- p1[0], 0.8*green);
draw(o -- p1[0], 0.8*green);
pair p1[] = intersectionpoints(c1, t1[1]);
draw(i2 -- p1[0], 0.8*green);
draw(o -- p1[0], 0.8*green);
line t1[] = tangents(c1, i3);
pair p1[] = intersectionpoints(c1, t1[0]);
draw(i3 -- p1[0], 0.8*blue);
draw(o -- p1[0], 0.8*blue);
pair p1[] = intersectionpoints(c1, t1[1]);
draw(i3 -- p1[0], 0.8*blue);
draw(o -- p1[0], 0.8*blue);
draw(a -- i1, red);
line pbc = perpendicular(midpoint(line(t.VB, t.VC)), line(t.VB, t.VC));
pair ic[] = intersectionpoints(c1, pbc);
draw(ic[0] -- ic[1], red);
label("$D$", ic[0], align=S, red);
label("$M$", ic[1], align=N, red);
draw(b -- ic[0], 0.7*green);
draw(c -- ic[0], 0.7*green);
draw(b -- ic[1], 0.7*green);
draw(i -- b, 0.7*green);
draw(i -- c, 0.7*green);
clipdraw(excircle(t.BC), 0.7*blue);
point p = relpoint(line(a, b), 2);
point s[] = intersectionpoints(excircle(t.BC), line(a,b));
label("$S$", s[0], align=NW, 0.7*green);
draw(b -- p, 0.7*green);
draw(i1 -- s[0], 0.7*green);
point p = relpoint(line(a, c), 3);
point t[] = intersectionpoints(excircle(t.BC), line(a,c));
label("$T$", t[0], align=NE, 0.7*green);
draw(c -- p, 0.7*green);
draw(i1 -- t[0], 0.7*green);
