settings.outformat = "png";
defaultpen(fontsize(14pt));
import geometry;

size(16cm);

pair a = (0, 1.5);
pair b = (-1, 0);
pair c = (1, 0);

show(triangle(a,b,c), La="", Lb="", Lc="", 0.7*green);
circle i = incircle(triangle(a,b,c));
draw(i, 0.5*green+0.8*blue);
pair c1[] = intersectionpoints(i, line(a, b));
line p1 = perpendicular(c1[0], line(a,b));
pair c2[] = intersectionpoints(i, p1);
line t1 = tangent(i, c2[0]);
pair p2 = intersectionpoint(t1, line(b, c));
pair p3 = intersectionpoint(t1, line(a, c));
draw(p2 -- p3, 0.7*green);
markangle("$B$", radius=10, c,b,a, 0.5*green+0.8*blue);
markangle("$A$", radius=10, b,a,c, 0.5*green+0.8*blue);
markangle("$C$", radius=10, a,c,b, 0.5*green+0.8*blue);
markangle("$B$", radius=10, c,p2,p3, 0.5*green+0.8*blue);
markangle("$A$", radius=10, p2,p3,c, 0.5*green+0.8*blue);
label("$T$", p2, align=S, 0.7*green);
label("$U$", p3, align=E, 0.7*green);
pair c1[] = intersectionpoints(i, line(b, c));
line p1 = perpendicular(c1[0], line(b,c));
pair c2[] = intersectionpoints(i, p1);
line t1 = tangent(i, c2[1]);
pair p2 = intersectionpoint(t1, line(a, b));
pair p3 = intersectionpoint(t1, line(a, c));
markangle("$B$", radius=10, p3,p2,a, 0.5*green+0.8*blue);
markangle("$C$", radius=10, a,p3,p2, 0.5*green+0.8*blue);
label("$P$", p2, align=W, 0.7*green);
label("$Q$", p3, align=E, 0.7*green);
draw(p2 -- p3, 0.7*green);
pair c1[] = intersectionpoints(i, line(a, c));
line p1 = perpendicular(c1[0], line(a,c));
pair c2[] = intersectionpoints(i, p1);
line t1 = tangent(i, c2[0]);
pair p2 = intersectionpoint(t1, line(a, b));
pair p3 = intersectionpoint(t1, line(b, c));
draw(p2 -- p3, 0.7*green);
markangle("$A$", radius=10, b,p2,p3, 0.5*green+0.8*blue);
markangle("$C$", radius=10, p2,p3,b, 0.5*green+0.8*blue);
label("$R$", p2, align=W, 0.7*green);
label("$S$", p3, align=S, 0.7*green);
