settings.outformat = "png";
defaultpen(fontsize(14pt));
import geometry;

size(16cm);

pair a = (0,3);
pair b = (-2,0);
pair c = (3,0);
triangle t = triangle(a,b,c);
show(La="", Lb="", Lc="", t, 0.7*green);
pair o = circumcenter(t);
pair i = incenter(t);
path cc = circle(t);
draw(cc, 0.7*green);
draw(o -- b, 0.5*green+0.8*blue+dashed);
draw(o -- c, 0.5*green+0.8*blue+dashed);
line l = perpendicular(i, line(b,c));
draw(i -- intersectionpoint(l, line(b,c)), 0.5*green+0.8*blue);
pair p[] = intersectionpoints(l, cc);
pair j = intersectionpoint(l, line(b,c));
real d = sqrt((j.x - p[1].x)*(j.x - p[1].x) + (j.y - p[1].y)*(j.y - p[1].y));
pair q = midpoint(line(j, p[1]));
circle cd = circle(midpoint(line(j, p[1])), d/2);
draw(cd, 0.5*green+0.8*blue);
draw(i -- q, 0.5*green+0.8*blue);
draw(o -- q, 0.5*green+0.8*blue);
line m = line(o, q);
pair p1[] = intersectionpoints(m, cd);
draw(o -- p1[0], 0.5*green+0.8*blue);
draw(o -- p1[1], 0.5*green+0.8*blue);
draw(o -- (o.x, q.y), 0.5*green+0.8*blue);
draw(q -- (o.x, q.y), 0.5*green+0.8*blue);
label("$O$", o, align=N, 0.5*green+0.8*blue);
label("$I$", i, align=N, 0.5*green+0.8*blue);
label("$D$", j, align=NE, 0.5*green+0.8*blue);
label("$P$", q, align=SE, 0.5*green+0.8*blue);
label("$Q$", p1[0], align=S, 0.5*green+0.8*blue);
label("$N$", (o.x, q.y), align=SE, 0.5*green+0.8*blue);
label("$M$", intersectionpoint(line(o, (o.x, q.y)), line(b,c)), align=NE, 0.5*green+0.8*blue);
label("$x$", midpoint(line(j,q))+(-.1, 0), 0.5*green+0.8*blue);
label("$x$", midpoint(line(q, p1[0]))+(-.1, 0), 0.5*green+0.8*blue);
